# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wedin_bound_resampling_cpp_draws <- function(X, signal_basis, right_vectors, draws) {
    .Call(`_rajiveplus_wedin_bound_resampling_cpp_draws`, X, signal_basis, right_vectors, draws)
}

random_direction_bound_cpp_draws <- function(n_obs, dims, draws_by_block) {
    .Call(`_rajiveplus_random_direction_bound_cpp_draws`, n_obs, dims, draws_by_block)
}

RobRSVD1_cpp <- function(data, sinit, uinit, vinit, huberk = 1.345, niter = 1000L, tol = 1e-5) {
    .Call(`_rajiveplus_RobRSVD1_cpp`, data, sinit, uinit, vinit, huberk, niter, tol)
}

RobRSVD_all_cpp <- function(data, nrank, sinit1, uinit1, vinit1, huberk = 1.345, niter = 1000L, tol = 1e-5) {
    .Call(`_rajiveplus_RobRSVD_all_cpp`, data, nrank, sinit1, uinit1, vinit1, huberk, niter, tol)
}

